Fixed target folder check in rsync script

diff --git a/usr/share/mackup/run/rsync b/usr/share/mackup/run/rsync
--- a/usr/share/mackup/run/rsync
+++ b/usr/share/mackup/run/rsync
@@ -6,6 +6,7 @@ exec 2>&1
 
 source="$(dirname $1)/$(basename $1)"
 target="./"
+dest=$target
 opts="-av"
 
 if [ ! -z "$REMOTE_HOST" ]; then
@@ -29,7 +30,7 @@ if [ ! -z "$INCREMENTAL_MONTHLY" ]; then
     lastmonth=$(date -d '1 month ago' +'%b' | awk '{print tolower($1)}')
     echo "attempting monthly incremental backup: last=$lastmonth cur=$curmonth"
     lasttarget="$(realpath $target)/$lastmonth/$(basename $source)"
-    newtarget="$target/$curmonth/$(basename $source)"
+    dest="$target/$curmonth/$(basename $source)"
     if [ -d "$lasttarget" ]; then
         echo "found last month's backup: $lasttarget"
         opts="$opts --link-dest=$(dirname $lasttarget)/"
@@ -49,7 +50,7 @@ elif [ ! -z "$INCREMENTAL_DAILY" ]; then
     lastday=$(date -d 'yesterday' +'%a' | awk '{print tolower($1)}')
     echo "attempting daily incremental backup: last=$lastday cur=$curday"
     lasttarget="$(realpath $target)/$lastday/$(basename $source)"
-    newtarget="$target/$curday"
+    dest="$target/$curday"
     if [ -d "$lasttarget" ]; then
         echo "found yesterday's backup: $lasttarget"
         opts="$opts --link-dest=$(dirname $lasttarget)/"
@@ -58,10 +59,14 @@ elif [ ! -z "$INCREMENTAL_DAILY" ]; then
     fi
 fi
 
-if [ ! -d "$newtarget" ]; then
-    mkdir -p "$newtarget"
+if [ ! -d "$dest" ]; then
+    mkdir -p "$dest" > /dev/null 2>&1
+    if [ ! $? = 0 ]; then
+        echo "error: failed to created destination directory '$dest'"
+        exit 1
+    fi
 fi
 
-echo "rsync $opts $source $newtarget"
+echo "rsync $opts $source $dest"
 
-exec rsync $opts $source $newtarget
+exec rsync $opts $source $dest
